<a href="https://colab.research.google.com/github/aserdargun/DSML101/blob/main/tensorflow/00_tensorflow_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

# IMPORTS

In [ ]:
import tensorflow as tf

# Solution 1.Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector = tf.constant([1, 2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
matrix = tf.constant([[1, 2],
                     [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8 , 9]],
                        [[10, 11, 12],
                         [13, 14 , 15],
                         [16, 17, 18]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

# Solution 2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 3, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=18>)

# Solution 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [ ]:
random_1 = tf.random.Generator.from_seed(1)
random_1 = random_1.uniform(shape=[5, 300])
random_2 = tf.random.Generator.from_seed(2)
random_2 = random_2.uniform(shape=(5, 300))
random_1, random_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.78749514, 0.3906511 , 0.29263055, ..., 0.50973356, 0.31043375,
         0.07893777],
        [0.57783425, 0.16236854, 0.63097   , ..., 0.5442884 , 0.10470831,
         0.43884432],
        [0.19212842, 0.40920782, 0.6351969 , ..., 0.15571809, 0.59350574,
         0.21187031],
        [0.06828582, 0.6658218 , 0.02978647, ..., 0.06306279, 0.91214204,
         0.46108627],
        [0.17251897, 0.9006287 , 0.5701351 , ..., 0.1984731 , 0.03311932,
         0.38387823]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.95810425, 0.55623317, 0.16466296, ..., 0.16236854, 0.63097   ,
         0.7254863 ],
        [0.8393048 , 0.89883757, 0.64980876, ..., 0.40920782, 0.6351969 ,
         0.9512656 ],
        [0.49248278, 0.09101331, 0.01480031, ..., 0.6658218 , 0.02978647,
         0.07853341],
        [0.4606458 , 0.8413516 , 0.241979  , ..., 0.9006287 , 0.5701351 ,
         0.2826221 ],
        [0.11323

# Solution 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
random_1.shape, random_2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [ ]:
tf.matmul(tf.transpose(random_1), random_2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.3850926 , 1.1841534 , 0.6060825 , ..., 0.6841954 , 1.0299499 ,
        1.1945064 ],
       [1.1207815 , 1.753161  , 0.7627978 , ..., 1.6830157 , 1.3750333 ,
        0.8624469 ],
       [1.2010517 , 1.3144623 , 0.7443481 , ..., 1.186584  , 1.0224358 ,
        1.0001314 ],
       ...,
       [1.0734144 , 1.0146307 , 0.5490147 , ..., 0.6160473 , 0.8475794 ,
        0.96263415],
       [1.1015261 , 1.1173812 , 0.36431852, ..., 1.3349662 , 0.82340753,
        0.636734  ],
       [0.80416393, 1.1833627 , 0.5943589 , ..., 1.0390071 , 0.86781853,
        0.7087432 ]], dtype=float32)>

# Solution 5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.tensordot(random_1, random_2, axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[7.54502416e-01, 4.38030928e-01, 1.29671276e-01, ...,
          1.27864435e-01, 4.96885806e-01, 5.71316898e-01],
         [6.60948455e-01, 7.07830191e-01, 5.11721253e-01, ...,
          3.22249174e-01, 5.00214517e-01, 7.49117017e-01],
         [3.87827784e-01, 7.16725439e-02, 1.16551723e-02, ...,
          5.24331450e-01, 2.34566983e-02, 6.18446805e-02],
         [3.62756312e-01, 6.62560344e-01, 1.90557286e-01, ...,
          7.09240735e-01, 4.48978633e-01, 2.22563535e-01],
         [8.91736075e-02, 6.92941546e-01, 3.72305840e-01, ...,
          5.95478177e-01, 5.54019094e-01, 1.78607628e-01]],

        [[3.74284476e-01, 2.17293099e-01, 6.43257648e-02, ...,
          6.34294450e-02, 2.46489123e-01, 2.83412009e-01],
         [3.27875346e-01, 3.51131886e-01, 2.53848523e-01, ...,
          1.59857482e-01, 2.48140380e-01, 3.71612936e-01],
         [1.92388937e-01, 3.55544500e-02, 5.78175765e-03, ...,
          2.60104030e-0

# Solution 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [ ]:
tensor_random = tf.random.Generator.from_seed(1).uniform(shape=[224, 224, 3])
tensor_random

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.78749514, 0.3906511 , 0.29263055],
        [0.99216926, 0.95810425, 0.55623317],
        [0.16466296, 0.13445711, 0.13229859],
        ...,
        [0.7011992 , 0.73613393, 0.4360633 ],
        [0.7536833 , 0.01353109, 0.2823602 ],
        [0.0927937 , 0.2424469 , 0.92214036]],

       [[0.1318667 , 0.18895125, 0.13469017],
        [0.29916108, 0.22880554, 0.02310789],
        [0.3042692 , 0.7830497 , 0.21773398],
        ...,
        [0.69211054, 0.67284966, 0.43589175],
        [0.48166   , 0.14082742, 0.41235518],
        [0.45162737, 0.6804353 , 0.04887676]],

       [[0.6775023 , 0.29143417, 0.3466624 ],
        [0.17450547, 0.38451958, 0.33060753],
        [0.73888445, 0.4587338 , 0.81736076],
        ...,
        [0.48929954, 0.97561824, 0.5725883 ],
        [0.8036673 , 0.3923154 , 0.4012767 ],
        [0.25327802, 0.7235824 , 0.51754737]],

       ...,

       [[0.21750414, 0.9080095 , 0.20064199],
        [0.31

# Solution 7. Find the min and max values of the tensor you created in 6.


In [ ]:
tf.reduce_min(tensor_random), tf.reduce_max(tensor_random)

(<tf.Tensor: shape=(), dtype=float32, numpy=4.053116e-06>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99998736>)

# Solution 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.


In [ ]:
new_random_tensor = tf.random.Generator.from_seed(1).uniform(shape=[1, 224, 224, 3])
squeezed_tensor = tf.squeeze(new_random_tensor)
new_random_tensor.shape, squeezed_tensor.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

# Solution 9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.


In [ ]:
tensor = tf.constant([11, 2, 3, 4 ,15 ,6 ,7 ,8, 9, 10])
tensor.shape, tf.argmax(tensor)

(TensorShape([10]), <tf.Tensor: shape=(), dtype=int64, numpy=4>)

# Solution 10. One-hot encode the tensor you created in 9.

In [ ]:
tf.one_hot(tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>